// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutDocumentDataSlicesSlice = TextBlockSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

type HomeDocumentDataSlicesSlice =
  TextBlockSlice | ProjectSlice | VideoBlockSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;

  /**
   * Newsletter Text field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: We have a newsletter! Sign up for occasional updates (if you like)
   * - **API ID Path**: home.newsletter_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  newsletter_text: prismic.KeyTextField;

  /**
   * Newsletter Button Label field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: subscribe
   * - **API ID Path**: home.newsletter_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  newsletter_label: prismic.KeyTextField;

  /**
   * Newsletter Link field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.newsletter_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  newsletter_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type ProjectDocumentDataSlicesSlice =
  ImageMultipleSlice | TextBlockSlice | VideoBlockSlice;

type ProjectDocumentDataSlices1Slice = never;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Cover field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover: prismic.ImageField<"4:5" | "1:1" | "3:2" | "16:9" | "5:4" | "4:3">;

  /**
   * Index only (no grid card, no link) field in *Project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.index_only
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  index_only: prismic.BooleanField;

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>; /**
   * About Text field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.about_text
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  about_text: prismic.RichTextField;

  /**
   * Client field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.client
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  client: prismic.RichTextField;

  /**
   * Date field in *Project*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project.date
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * More field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.more
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  more: prismic.RichTextField;

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices1[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices1: prismic.SliceZone<ProjectDocumentDataSlices1Slice>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes = AboutDocument | HomeDocument | ProjectDocument;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageMultipleSliceDefaultPrimary {
  /**
   * Auto-play carousel field in *Image → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_multiple.default.primary.carousel
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  carousel: prismic.BooleanField;

  /**
   * Progress on hover field in *Image → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_multiple.default.primary.carousel_hover
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  carousel_hover: prismic.BooleanField;
}

/**
 * Primary content in *Image → Items*
 */
export interface ImageMultipleSliceDefaultItem {
  /**
   * Image field in *Image → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_multiple.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<"4:5" | "1:1" | "3:2" | "16:9" | "5:4" | "4:3">;

  /**
   * Ratio field in *Image → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: main
   * - **API ID Path**: image_multiple.items[].ratio
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  ratio: prismic.SelectField<
    "main" | "16:9" | "5:4" | "4:5" | "4:3" | "1:1" | "3:2",
    "filled"
  >;

  /**
   * Size field in *Image → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Full
   * - **API ID Path**: image_multiple.items[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"Full" | "Regular", "filled">;

  /**
   * Drop shadow field in *Image → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_multiple.items[].shadow
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  shadow: prismic.BooleanField;

  /**
   * Hide from project grid preview field in *Image → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_multiple.items[].hide_from_grid
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hide_from_grid: prismic.BooleanField;

  /**
   * Link field in *Image → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_multiple.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Caption field in *Image → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_multiple.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;

  /**
   * Show Caption field in *Image → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_multiple.items[].show_caption
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_caption: prismic.BooleanField;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageMultiple
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageMultipleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageMultipleSliceDefaultPrimary>,
  Simplify<ImageMultipleSliceDefaultItem>
>;

/**
 * Slice variation for *Image*
 */
type ImageMultipleSliceVariation = ImageMultipleSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image_multiple`
 * - **Description**: ImageMultiple
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageMultipleSlice = prismic.SharedSlice<
  "image_multiple",
  ImageMultipleSliceVariation
>;

/**
 * Primary content in *Project → Items*
 */
export interface ProjectSliceDefaultItem {
  /**
   * Project field in *Project → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.items[].project
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * Image field in *Project → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<"4:5" | "1:1" | "3:2" | "16:9" | "5:4" | "4:3">;

  /**
   * Ratio field in *Project → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: main
   * - **API ID Path**: project.items[].ratio
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  ratio: prismic.SelectField<
    "main" | "16:9" | "5:4" | "4:5" | "4:3" | "1:1" | "3:2",
    "filled"
  >;

  /**
   * Size field in *Project → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Full
   * - **API ID Path**: project.items[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"Full" | "Regular", "filled">;

  /**
   * Drop shadow field in *Project → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.items[].shadow
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  shadow: prismic.BooleanField;

  /**
   * Link field in *Project → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Caption field in *Project → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;

  /**
   * Show Caption field in *Project → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: project.items[].show_caption
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_caption: prismic.BooleanField;
}

/**
 * Default variation for Project Slice
 *
 * - **API ID**: `default`
 * - **Description**: Project
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ProjectSliceDefaultItem>
>;

/**
 * Slice variation for *Project*
 */
type ProjectSliceVariation = ProjectSliceDefault;

/**
 * Project Shared Slice
 *
 * - **API ID**: `project`
 * - **Description**: Project
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSlice = prismic.SharedSlice<
  "project",
  ProjectSliceVariation
>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Text field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

/**
 * Primary content in *VideoBlock → Default → Primary*
 */
export interface VideoBlockSliceDefaultPrimary {
  /**
   * Video Source field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Vimeo
   * - **API ID Path**: video_block.default.primary.video_source
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  video_source: prismic.SelectField<"Vimeo" | "Gumlet", "filled">;

  /**
   * Vimeo Embed field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.vimeo_embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  vimeo_embed: prismic.EmbedField;

  /**
   * Gumlet Stream URL field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://video.gumlet.io/<collection-id>/<asset-id>/main.m3u8
   * - **API ID Path**: video_block.default.primary.gumlet_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gumlet_url: prismic.KeyTextField;

  /**
   * Gumlet Poster Image field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.gumlet_poster
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  gumlet_poster: prismic.ImageField<never>;

  /**
   * Gumlet Aspect Ratio field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 16:9
   * - **API ID Path**: video_block.default.primary.gumlet_ratio
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  gumlet_ratio: prismic.SelectField<
    "16:9" | "4:5" | "1:1" | "5:4" | "4:3" | "3:2" | "21:9" | "Auto",
    "filled"
  >;

  /**
   * Size field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Full
   * - **API ID Path**: video_block.default.primary.size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"Full" | "Regular", "filled">;

  /**
   * Background field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: video_block.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<"None" | "Black", "filled">;

  /**
   * Custom Caption field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.custom_caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  custom_caption: prismic.KeyTextField;

  /**
   * Show Caption field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: video_block.default.primary.show_caption
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_caption: prismic.BooleanField;
}

/**
 * Default variation for VideoBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBlock*
 */
type VideoBlockSliceVariation = VideoBlockSliceDefault;

/**
 * VideoBlock Shared Slice
 *
 * - **API ID**: `video_block`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoBlockSlice = prismic.SharedSlice<
  "video_block",
  VideoBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ProjectDocumentDataSlices1Slice,
      AllDocumentTypes,
      ImageMultipleSlice,
      ImageMultipleSliceDefaultPrimary,
      ImageMultipleSliceDefaultItem,
      ImageMultipleSliceVariation,
      ImageMultipleSliceDefault,
      ProjectSlice,
      ProjectSliceDefaultItem,
      ProjectSliceVariation,
      ProjectSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      VideoBlockSlice,
      VideoBlockSliceDefaultPrimary,
      VideoBlockSliceVariation,
      VideoBlockSliceDefault,
    };
  }
}
