// This file is generated by Slice Machine. Update with care!

import DetailBlock from './DetailBlock';
import ImageSingle from './ImageSingle';
import ProjectPair from './ProjectPair';
import ProjectSingle from './ProjectSingle';
import TextBlock from './TextBlock';

export {
	DetailBlock,
	ImageSingle,
	ProjectPair,
	ProjectSingle,
	TextBlock,
};

export const components = {
	column_block: DetailBlock,
	image_single: ImageSingle,
	project_pair: ProjectPair,
	project_single: ProjectSingle,
	text_block: TextBlock,
};
