// Code generated by Slice Machine. DO NOT EDIT.

import DetailBlock from './DetailBlock';
import Image from './Image';
import Project from './Project';
import TextBlock from './TextBlock';
import VideoBlock from './VideoBlock';

export {
	DetailBlock,
	Image,
	Project,
	TextBlock,
	VideoBlock,
};

export const components = {
	column_block: DetailBlock,
	image_multiple: Image,
	project: Project,
	text_block: TextBlock,
	video_block: VideoBlock,
};
